Employees/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

using Employees.Helpers;
using Employees.Models;
using Employees.Models.EmployeeVM;

namespace Employees.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IConfiguration config;
        private readonly OrganizationContext context;

        public EmployeeController(IConfiguration config, OrganizationContext context)
        {
            this.config = config;
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            var employees = await context.Employees
                .Include(p => p.Position)
                .AsNoTracking()
                .ToListAsync();

            string dateFormat = config.GetValue<string>("Birthdate:Format");
            IEnumerable<EmployeePreviewVM> employeesPreview = employees.Select(e => new EmployeePreviewVM
            {
                Id = e.Id,
                Name = e.Name,
                Patronymic = e.Patronymic,
                Surname = e.Surname,
                Gender = GenderHelper.GetValue(e.Gender),
                Position = e.Position.Name,
                Birthdate = e.Birthdate.ToString(dateFormat),
                Phone = e.Phone
            });

            return View(employeesPreview);
        }

        /// <summary>
        /// Create dropdown list for Genders
        /// </summary>
        private SelectList CreateGendersDropDownList() => new SelectList(GenderHelper.CreateList(), "Value", "Text");

        /// <summary>
        /// Create dropdown list for Positions
        /// </summary>
        private SelectList CreatePositionsDropDownList() => new SelectList(context.Positions.ToList(), "Id", "Name");

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        public IActionResult Add()
        {
            ViewData["Genders"] = CreateGendersDropDownList();
            ViewData["Positions"] = CreatePositionsDropDownList();

            return View();
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(EmployeeAddVM model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Genders"] = CreateGendersDropDownList();
                ViewData["Positions"] = CreatePositionsDropDownList();

                return View(model);
            }

            Employee employee = new Employee
            {
                Name = model.Name,
                Patronymic = model.Patronymic,
                Surname = model.Surname,
                Gender = model.Gender,
                PositionId = model.Position,
                Birthdate = model.Birthdate,
                Phone = model.Phone
            };

            context.Employees.Add(employee);
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Employee employee = await context.Employees
                .Include(p => p.Position)
                .FirstOrDefaultAsync(e => e.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            EmployeeEditVM model = new EmployeeEditVM
            {
                Id = employee.Id,
                Name = employee.Name,
                Patronymic = employee.Patronymic,
                Surname = employee.Surname,
                Gender = employee.Gender,
                Position = employee.Position.Id,
                Birthdate = employee.Birthdate,
                Phone = employee.Phone
            };

            ViewData["Genders"] = CreateGendersDropDownList();
            ViewData["Positions"] = CreatePositionsDropDownList();

            return View(model);
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeEditVM model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Genders"] = CreateGendersDropDownList();
                ViewData["Positions"] = CreatePositionsDropDownList();

                return View(model);
            }

            Employee employeeToEdit = await context.Employees.FirstOrDefaultAsync(e => e.Id == model.Id);
            if (employeeToEdit == null)
            {
                return NotFound();
            }

            employeeToEdit.Name = model.Name;
            employeeToEdit.Patronymic = model.Patronymic;
            employeeToEdit.Surname = model.Surname;
            employeeToEdit.Gender = model.Gender;
            employeeToEdit.PositionId = model.Position;
            employeeToEdit.Birthdate = model.Birthdate;
            employeeToEdit.Phone = model.Phone;

            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Employee employee = new Employee { Id = id.Value };
            context.Entry(employee).State = EntityState.Deleted;
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [Authorize]
        [ActionName("Genders")]
        public async Task<IActionResult> GetGenderRates()
        {
            int totalEmployees = await context.Employees.CountAsync();
            int males = await context.Employees.CountAsync(e => e.Gender == 1);
            double malePercent = (double)males / totalEmployees * 100;
            int females = await context.Employees.CountAsync(e => e.Gender == 2);
            double femalePercent = (double)females / totalEmployees * 100;

            var gendersData = new[]
            {
                new
                {
                    gender = "male",
                    rate = malePercent
                },
                new
                {
                    gender = "female",
                    rate = femalePercent
                }
            };

            ViewData["GenderData"] = JsonSerializer.Serialize(gendersData);

            return View();
        }

        [Authorize]
        [ActionName("BirthDecade")]
        public async Task<IActionResult> GetBirthDecadeRates()
        {
            int totalEmployees = await context.Employees.CountAsync();
            List<int> birthdates = await context.Employees.Select(e => AgeHelper.GetDecade(e.Birthdate))
                .ToListAsync();

            var decadesData = birthdates.GroupBy(e => e)
                .Select(g => new
                 {
                     decade = g.Key.ToString(),
                     rate = (double)g.Count() / totalEmployees * 100
                 });

            ViewData["DecadeData"] = JsonSerializer.Serialize(decadesData);

            return View();
        }
    }
}

Employees/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

using Employees.Helpers;
using Employees.Models;
using Employees.Models.UserVM;

namespace Employees.Controllers
{
    public class UserController : Controller
    {
        private readonly IConfiguration config;
        private readonly OrganizationContext context;

        public UserController(IConfiguration config, OrganizationContext context)
        {
            this.config = config;
            this.context = context;
        }

        // GET: User
        public async Task<IActionResult> Index()
        {
            var users = await context.Users.AsNoTracking().ToListAsync();

            IEnumerable<UserPreviewVM> userPreviewVM = users.Select(u => new UserPreviewVM
            {
                Id = u.Id,
                Login = u.Login
            });

            return View(userPreviewVM);
        }

        // GET: User/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await context.Users
                .Include(u => u.Employee)
                .ThenInclude(u => u.Position)
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            string dateFormat = config.GetValue<string>("Birthdate:Format");
            UserDetailsVM userDetails = new UserDetailsVM
            {
                Id = user.Id,
                Login = user.Login,
                Role = user.Role.Name,
                Name = user.Employee.Name,
                Patronymic = user.Employee.Patronymic,
                Surname = user.Employee.Surname,
                Gender = GenderHelper.GetValue(user.Employee.Gender),
                Position = user.Employee.Position.Name,
                Birthdate = user.Employee.Birthdate.ToString(dateFormat),
                Phone = user.Employee.Phone
            };

            return View(userDetails);
        }

        /// <summary>
        /// Create dropdown list for Roles
        /// </summary>
        private SelectList CreateRolesDropDownList() => new SelectList(context.Roles.ToList(), "Id", "Name");

        /// <summary>
        /// Create dropdown list for Employees without account
        /// </summary>
        private SelectList CreateEmployeesWithoutAccountDropDownList()
        {
            var employeesWithoutAccount = from e in context.Employees
                                          where !context.Users.Any(u => u.EmployeeId == e.Id)
                                          select new
                                          {
                                              e.Id,
                                              Details = $"{e.Name} {e.Patronymic} {e.Surname} (возраст: {AgeHelper.GetAge(e.Birthdate)}) - {e.Position.Name}"
                                          };

            return new SelectList(employeesWithoutAccount.ToList(), "Id", "Details");
        }

        // GET: User/Create
        public IActionResult Create()
        {
            ViewData["Roles"] = CreateRolesDropDownList();
            ViewData["Employees"] = CreateEmployeesWithoutAccountDropDownList();

            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserCreateVM model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Roles"] = CreateRolesDropDownList();
                ViewData["Employees"] = CreateEmployeesWithoutAccountDropDownList();

                return View(model);
            }

            User user = new User
            {
                Login = model.Login,
                Password = model.Password,
                RoleId = model.Role,
                EmployeeId = model.Employee
            };

            context.Add(user);
            await context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: User/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await context.Users
                .FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            UserEditVM model = new UserEditVM
            {
                Id = user.Id,
                Login = user.Login,
                Password = user.Password,
                Role = user.RoleId,
            };

            ViewData["Roles"] = CreateRolesDropDownList();

            return View(model);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditVM model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Roles"] = CreateRolesDropDownList();

                return View(model);
            }

            User userToEdit = await context.Users.FirstOrDefaultAsync(u => u.Id == model.Id);
            if (userToEdit == null)
            {
                return NotFound();
            }

            userToEdit.Login = model.Login;
            
            if (!string.IsNullOrEmpty(model.Password))
            {
                userToEdit.Password = model.Password;
            }

            userToEdit.RoleId = model.Role;

            await context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }

        // GET: User/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User user = new User { Id = id.Value };
            context.Entry(user).State = EntityState.Deleted;
            await context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Employees/Views/Shared/_Layout.cshtml
@{
    var userName = (
        User != null &&
        User.Identity != null &&
        !string.IsNullOrEmpty(User.Identity.Name)) ? User.Identity.Name : null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Организация - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Организация</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav flex-grow-1">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="navbar-text">@Html.ActionLink("Сотрудники", "Index", "Employee")</li>
                            <li>&nbsp;&nbsp;</li>
                            <li class="navbar-text">@Html.ActionLink("Отчет по полам", "Genders", "Employee")</li>
                            <li>&nbsp;&nbsp;</li>
                            <li class="navbar-text">@Html.ActionLink("Отчет по десятилетиям", "BirthDecade", "Employee")</li>
                        }

                        @if (User.IsInRole("Администратор"))
                        {
                            <li>&nbsp;&nbsp;</li>
                            <li class="navbar-text">@Html.ActionLink("Пользователи", "Index", "User")</li>
                        }

                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav flex-grow-1">
                        <li class="navbar-text">
                            Hello,
                            @(userName ?? "Гость")!
                        </li>
                        <li>&nbsp;&nbsp;</li>

                        @if (userName != null)
                        {
                            <li class="navbar-text">@Html.ActionLink("Выход", "Logout", "Account")</li>
                        }
                        else
                        {
                            <li class="navbar-text">@Html.ActionLink("Войти", "Login", "Account")</li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Организация
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>